name: Mirror budal12.net

on:
  schedule:
    - cron: "*/10 * * * *"  # 매 10분마다 실행
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Download budal12.net page
        run: curl -s -A "Mozilla/5.0" https://budal12.net/pr_kiss > index.html

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Update mirror at $(date)" || echo "No changes to commit"
          git push
