name: Mirror budal12.net

on:
  schedule:
    - cron: '*/10 * * * *'  # 10분마다 실행
  workflow_dispatch:

permissions:
  contents: write  # 🔥 푸시 권한 설정 필수!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Get budal12 page
        run: curl -L https://budal12.net/pr_kiss > index.html

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Update mirror at $(date)" || echo "No changes"
          git push
